# Site settings
title: Info om udveksling
header-img: img/worldmap1.jpg
email: annx2997@5500middelfart.dk
copyright_name: Ann-Cathrine Thrane
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "http://ann-cathrine.github.io/"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  annx2997@5500middelfart.dk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
